---
- name: Infrastructure-as-Code simple demo
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    iac_var1: "iac_var1 from playbook"
    iac_var2: "iac_var2 from playbook"
  tasks:
    - name: Block to get new variables
      when: control_file is defined
      block:
        - name: Get contents of control_file
          ansible.builtin.tempfile:
            state: file
          register: tmp_varfile
          notify: Remove varfile

        - name: Print value of tmp_varfile
          ansible.builtin.debug:
            var: tmp_varfile

        - name: Write contents of url to file
          ansible.builtin.copy:
            dest: "{{ tmp_varfile.path }}"
            content: "{{ lookup('ansible.builtin.url', control_file, split_lines=False) }}"
            mode: "0600"

        - name: Debug print contents of control_file
          ansible.builtin.debug:
            msg: "{{ lookup('ansible.builtin.url', control_file, split_lines=False) }}"

        - name: Include vars from file tempfile
          ansible.builtin.include_vars:
            file: "{{ tmp_varfile.path }}"


    - name: Print value of iac_var1
      ansible.builtin.debug:
        var: iac_var1

    - name: Print the value of iac_var2
      ansible.builtin.debug:
        var: iac_var2

  handlers:
    - name: Remove varfile
      ansible.builtin.file:
        path: "{{ tmp_varfile.path }}"
        state: absent
      when: temp_varfile is defined
