# .github/workflows/lint.yml
name: ansible-lint
on:
  push:
    branches: ["main", "production"]
  pull_request:
    branches: ["main", "production"]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or version tag instead of 'main'
  call_aap:
    name: Call AAP if the push or pull meets criterial
    runs-on: ubunut-latest
    if: github.ref == 'refs/heads/production'
    steps:
      - uses: actions/checkout@v4
      - name: Load the ansible-cloud action
        id: controller_job
        uses: ansible-cloud/aap_controller_action@v1.2.8
        with:
          controller_host: ${{ secrets.CONTROLLER_HOST }}
          controller_username: ${{ secrets.CONTROLLER_USERNAME }}
          controller_password: ${{ secrets.CONTROLLER_PASSWORD }}
          job_template: "IAC Job Template"
          validate_certs: false
          extra_vars: "control_file=https://raw.githubusercontent.com/dcostakos/ansible_gitops_demo/production/iac.yml"
