# .github/workflows/lint.yml
name: Lint and Push
on:
  push:
    branches: ["main", "production"]
  pull_request:
    branches: ["main", "production"]
jobs:
  build:
    name: Ansible Lint # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@main # or version tag instead of 'main'
      - name: Call AAP if the push or pull meets criterial
        if: github.ref == 'refs/heads/production'
        id: controller_job
        uses: ansible-cloud/aap_controller_action@v1.2.8
        with:
          controller_host: ${{ secrets.CONTROLLER_HOST }}
          controller_username: ${{ secrets.CONTROLLER_USERNAME }}
          controller_password: ${{ secrets.CONTROLLER_PASSWORD }}
          job_template: "IAC Job Template"
          validate_certs: false
          extra_vars: "control_file=https://raw.githubusercontent.com/dcostakos/ansible_gitops_demo/production/iac.yml"
